#!/usr/bin/env python3
"""Merge aerospace.base.toml with a layout fragment and reload AeroSpace.

The AeroSpace config format has no `include`, so a two-monitor and a
three-monitor setup would otherwise be two ~300-line files differing in about
forty — and two copies drift. This keeps one base and small fragments, the same
arrangement windows/windows-terminal/apply-theme.py uses for its themes.

    ./apply-layout.py            detect screen count and apply the match
    ./apply-layout.py 2mon       force a layout
    ./apply-layout.py --dry-run  print what would change, write nothing

The generated aerospace.toml is git-ignored: it is an artifact, and the sources
are base + fragment. bootstrap.sh runs this before symlinking.
"""
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
BASE = HERE / "aerospace.base.toml"
OUT = HERE / "aerospace.toml"
AEROSPACE = "/opt/homebrew/bin/aerospace"
SECTIONS = ("PERSISTENT_WORKSPACES", "MONITOR_ASSIGNMENT", "WORKSPACE_BINDINGS", "APP_RULES")


def die(msg):
    print(f"apply-layout: {msg}", file=sys.stderr)
    sys.exit(1)


def count_monitors():
    """Ask AeroSpace, not the OS: it is the thing whose view has to match."""
    try:
        out = subprocess.run([AEROSPACE, "list-monitors"], capture_output=True,
                             text=True, timeout=10)
    except (OSError, subprocess.SubprocessError) as e:
        die(f"could not ask AeroSpace how many monitors it sees ({e}). "
            f"Pass a layout explicitly, e.g. 'apply-layout.py 2mon'.")
    if out.returncode != 0:
        die(f"aerospace list-monitors failed: {out.stderr.strip()}")
    return len([l for l in out.stdout.splitlines() if l.strip()])


def parse_fragment(path):
    """Split a fragment on its `# ---8<--- NAME` markers."""
    text = path.read_text()
    parts, name, buf = {}, None, []
    for line in text.split("\n"):
        m = re.match(r"^#\s*-+8<-+\s*([A-Z_]+)\s*$", line)
        if m:
            if name:
                parts[name] = "\n".join(buf).strip("\n")
            name, buf = m.group(1), []
        elif name:
            buf.append(line)
    if name:
        parts[name] = "\n".join(buf).strip("\n")
    missing = [s for s in SECTIONS if s not in parts]
    if missing:
        die(f"{path.name} is missing section(s): {', '.join(missing)}")
    return parts


def main():
    args = [a for a in sys.argv[1:] if a != "--dry-run"]
    dry = "--dry-run" in sys.argv[1:]

    if args:
        layout = args[0]
    else:
        n = count_monitors()
        # Everything that is not three screens gets the two-column layout: on a
        # single display the pair layout degrades to six workspaces on one
        # screen, which is right, while the three-column one hides a third of
        # them behind the others.
        layout = "3mon" if n >= 3 else "2mon"
        print(f"apply-layout: {n} monitor(s) -> {layout}")

    frag = HERE / f"layout-{layout}.toml"
    if not frag.exists():
        avail = ", ".join(sorted(p.stem.replace("layout-", "")
                                 for p in HERE.glob("layout-*.toml")))
        die(f"no layout '{layout}' (have: {avail})")

    parts = parse_fragment(frag)
    merged = BASE.read_text()
    for section in SECTIONS:
        token = f"@@{section}@@"
        if token not in merged:
            die(f"{BASE.name} has no {token} placeholder")
        merged = merged.replace(token, parts[section], 1)
    if "@@" in merged:
        die("a placeholder survived the merge — check the base file")

    merged = merged.replace(
        "# AeroSpace BASE — everything that does not depend on how many screens are",
        f"# GENERATED by apply-layout.py from aerospace.base.toml + layout-{layout}.toml.\n"
        f"# Do not edit this file — edit those two and re-run the script.\n"
        f"#\n"
        f"# AeroSpace BASE — everything that does not depend on how many screens are", 1)

    if dry:
        print(f"apply-layout: would write {OUT} from layout-{layout} "
              f"({len(merged.splitlines())} lines)")
        return

    OUT.write_text(merged)
    print(f"apply-layout: wrote {OUT.name} from layout-{layout}")

    check = subprocess.run([AEROSPACE, "reload-config", "--dry-run"],
                           capture_output=True, text=True)
    if check.returncode != 0 or "ERROR" in (check.stdout + check.stderr):
        die("the merged config does not parse — NOT reloading:\n"
            + (check.stdout + check.stderr).strip())
    subprocess.run([AEROSPACE, "reload-config"], check=False)
    print("apply-layout: reloaded")


if __name__ == "__main__":
    main()
